# Generated by Django 4.2.5 on 2023-09-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('bookTitle', models.CharField(max_length=150, null=True)),
                ('bookAuthor', models.CharField(max_length=50, null=True)),
                ('yearOfPublication', models.IntegerField(null=True)),
                ('publisher', models.CharField(max_length=50, null=True)),
                ('imageURLS', models.CharField(max_length=150, null=True)),
                ('imageURLM', models.CharField(max_length=150, null=True)),
                ('imageURLL', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('bookRating', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
